#!/bin/bash

mkdir straight; cp ../index.html straight/; cp ../storyboard.json straight/
mkdir clock; cp ../index.html clock/; cp ../storyboard.json clock/
mkdir scribble; cp ../index.html scribble/; cp ../storyboard.json scribble/
mkdir radius; cp ../index.html radius/; cp ../storyboard.json radius/
mkdir compass; cp ../index.html compass/; cp ../storyboard.json compass/
# mkdir two; cp ../index.html two/; cp ../storyboard.json two/
# mkdir blobs; cp ../index.html blobs/; cp ../storyboard.json blobs/
mkdir mono; cp ../index.html mono/; cp ../storyboard.json mono/
mkdir wall; cp ../index.html wall/; cp ../storyboard.json wall/
mkdir color; cp ../index.html color/; cp ../storyboard.json color/
mkdir analyze; cp ../index.html analyze/; cp ../storyboard.json analyze/
mkdir glyphs; cp ../index.html glyphs/; cp ../storyboard.json glyphs/
mkdir hexa; cp ../index.html hexa/; cp ../storyboard.json hexa/
mkdir spiral; cp ../index.html spiral/; cp ../storyboard.json spiral/
mkdir pond; cp ../index.html pond/; cp ../storyboard.json pond/
mkdir length; cp ../index.html length/; cp ../storyboard.json length/
mkdir shapes; cp ../index.html shapes/; cp ../storyboard.json shapes/
mkdir splat; cp ../index.html splat/; cp ../storyboard.json splat/
mkdir pearls; cp ../index.html pearls/; cp ../storyboard.json pearls/
mkdir laby; cp ../index.html laby/; cp ../storyboard.json laby/
mkdir flowers; cp ../index.html flowers/; cp ../storyboard.json flowers/
mkdir tooth; cp ../index.html tooth/; cp ../storyboard.json tooth/
mkdir polygon; cp ../index.html polygon/; cp ../storyboard.json polygon/
mkdir ends; cp ../index.html ends/; cp ../storyboard.json ends/
mkdir zorro; cp ../index.html zorro/; cp ../storyboard.json zorro/
mkdir grid; cp ../index.html grid/; cp ../storyboard.json grid/
mkdir typewriter; cp ../index.html typewriter/; cp ../storyboard.json typewriter/
mkdir grays; cp ../index.html grays/; cp ../storyboard.json grays/
mkdir lines; cp ../index.html lines/; cp ../storyboard.json lines/
mkdir cross; cp ../index.html cross/; cp ../storyboard.json cross/
mkdir autumn; cp ../index.html autumn/; cp ../storyboard.json autumn/
mkdir bucolic; cp ../index.html bucolic/; cp ../storyboard.json bucolic/
# mkdir pepper; cp ../index.html pepper/; cp ../storyboard.json pepper/
mkdir random; cp ../index.html random/; cp ../storyboard.json random/
mkdir blink; cp ../index.html blink/; cp ../storyboard.json blink/
mkdir fog; cp ../index.html fog/; cp ../storyboard.json fog/
mkdir noise; cp ../index.html noise/; cp ../storyboard.json noise/
mkdir copper; cp ../index.html copper/; cp ../storyboard.json copper/
mkdir black; cp ../index.html black/; cp ../storyboard.json black/
mkdir diamond; cp ../index.html diamond/; cp ../storyboard.json diamond/
mkdir photo; cp ../index.html photo/; cp ../storyboard.json photo/
mkdir book; cp ../index.html book/; cp ../storyboard.json book/
mkdir seeds; cp ../index.html seeds/; cp ../storyboard.json seeds/
mkdir migration; cp ../index.html migration/; cp ../storyboard.json migration/
mkdir eggs; cp ../index.html eggs/; cp ../storyboard.json eggs/
mkdir larvae; cp ../index.html larvae/; cp ../storyboard.json larvae/
mkdir xrays; cp ../index.html xrays/; cp ../storyboard.json xrays/
mkdir numeric; cp ../index.html numeric/; cp ../storyboard.json numeric/
mkdir import; cp ../index.html import/; cp ../storyboard.json import/
mkdir polaroid; cp ../index.html polaroid/; cp ../storyboard.json polaroid/
mkdir ordenador; cp ../index.html ordenador/; cp ../storyboard.json ordenador/
mkdir search; cp ../index.html search/; cp ../storyboard.json search/
mkdir carbon; cp ../index.html carbon/; cp ../storyboard.json carbon/
mkdir good; cp ../index.html good/; cp ../storyboard.json good/
mkdir tictactoe; cp ../index.html tictactoe/; cp ../storyboard.json tictactoe/
mkdir trouble; cp ../index.html trouble/; cp ../storyboard.json trouble/
mkdir pass; cp ../index.html pass/; cp ../storyboard.json pass/
mkdir draw; cp ../index.html draw/; cp ../storyboard.json draw/
mkdir marbles; cp ../index.html marbles/; cp ../storyboard.json marbles/
mkdir league; cp ../index.html league/; cp ../storyboard.json league/
mkdir math; cp ../index.html math/; cp ../storyboard.json math/
mkdir crypto; cp ../index.html crypto/; cp ../storyboard.json crypto/
mkdir circles; cp ../index.html circles/; cp ../storyboard.json circles/
mkdir crypt; cp ../index.html crypt/; cp ../storyboard.json crypt/
mkdir dots; cp ../index.html dots/; cp ../storyboard.json dots/
mkdir vibration; cp ../index.html vibration/; cp ../storyboard.json vibration/
mkdir mosaic; cp ../index.html mosaic/; cp ../storyboard.json mosaic/
mkdir soap; cp ../index.html soap/; cp ../storyboard.json soap/
mkdir wood; cp ../index.html wood/; cp ../storyboard.json wood/
mkdir mosaic; cp ../index.html mosaic/; cp ../storyboard.json mosaic/
mkdir wood; cp ../index.html wood/; cp ../storyboard.json wood/
mkdir stack; cp ../index.html stack/; cp ../storyboard.json stack/
mkdir clouds; cp ../index.html clouds/; cp ../storyboard.json clouds/
mkdir salt; cp ../index.html salt/; cp ../storyboard.json salt/
mkdir stars; cp ../index.html stars/; cp ../storyboard.json stars/
mkdir shuffling
