#!/bin/bash

sed -i -e 's/dist/javascripts/g' straight/index.html
sed -i -e 's/dist/javascripts/g'  clock/index.html
sed -i -e 's/dist/javascripts/g'  scribble/index.html
sed -i -e 's/dist/javascripts/g'  radius/index.html
sed -i -e 's/dist/javascripts/g'  compass/index.html
sed -i -e 's/dist/javascripts/g'  two/index.html
sed -i -e 's/dist/javascripts/g'  blobs/index.html
sed -i -e 's/dist/javascripts/g'  mono/index.html
sed -i -e 's/dist/javascripts/g'  wall/index.html
sed -i -e 's/dist/javascripts/g'  color/index.html
sed -i -e 's/dist/javascripts/g'  analyze/index.html
sed -i -e 's/dist/javascripts/g'  glyphs/index.html
sed -i -e 's/dist/javascripts/g'  hexa/index.html
sed -i -e 's/dist/javascripts/g'  spiral/index.html
sed -i -e 's/dist/javascripts/g'  pond/index.html
sed -i -e 's/dist/javascripts/g'  length/index.html
sed -i -e 's/dist/javascripts/g'  shapes/index.html
sed -i -e 's/dist/javascripts/g'  splat/index.html
sed -i -e 's/dist/javascripts/g'  pearls/index.html
sed -i -e 's/dist/javascripts/g'  laby/index.html
sed -i -e 's/dist/javascripts/g'  flowers/index.html
sed -i -e 's/dist/javascripts/g'  tooth/index.html
sed -i -e 's/dist/javascripts/g'  polygon/index.html
sed -i -e 's/dist/javascripts/g'  ends/index.html
sed -i -e 's/dist/javascripts/g'  zorro/index.html
sed -i -e 's/dist/javascripts/g'  grid/index.html
sed -i -e 's/dist/javascripts/g'  typewriter/index.html
sed -i -e 's/dist/javascripts/g'  grays/index.html
sed -i -e 's/dist/javascripts/g'  lines/index.html
sed -i -e 's/dist/javascripts/g'  cross/index.html
sed -i -e 's/dist/javascripts/g'  autumn/index.html
sed -i -e 's/dist/javascripts/g'  bucolic/index.html
sed -i -e 's/dist/javascripts/g'  pepper/index.html
sed -i -e 's/dist/javascripts/g'  random/index.html
sed -i -e 's/dist/javascripts/g'  blink/index.html
sed -i -e 's/dist/javascripts/g'  fog/index.html
sed -i -e 's/dist/javascripts/g'  noise/index.html
sed -i -e 's/dist/javascripts/g'  copper/index.html
sed -i -e 's/dist/javascripts/g'  black/index.html
sed -i -e 's/dist/javascripts/g'  diamond/index.html
sed -i -e 's/dist/javascripts/g'  photo/index.html
sed -i -e 's/dist/javascripts/g'  book/index.html
sed -i -e 's/dist/javascripts/g'  seeds/index.html
sed -i -e 's/dist/javascripts/g'  migration/index.html
sed -i -e 's/dist/javascripts/g'  eggs/index.html
sed -i -e 's/dist/javascripts/g'  larvae/index.html
sed -i -e 's/dist/javascripts/g'  xrays/index.html
sed -i -e 's/dist/javascripts/g'  numeric/index.html
sed -i -e 's/dist/javascripts/g'  import/index.html
sed -i -e 's/dist/javascripts/g'  polaroid/index.html
sed -i -e 's/dist/javascripts/g'  ordenador/index.html
sed -i -e 's/dist/javascripts/g'  search/index.html
sed -i -e 's/dist/javascripts/g'  carbon/index.html
sed -i -e 's/dist/javascripts/g'  good/index.html
sed -i -e 's/dist/javascripts/g'  tictactoe/index.html
sed -i -e 's/dist/javascripts/g'  trouble/index.html
sed -i -e 's/dist/javascripts/g'  pass/index.html
sed -i -e 's/dist/javascripts/g'  draw/index.html
sed -i -e 's/dist/javascripts/g'  marbles/index.html
sed -i -e 's/dist/javascripts/g'  league/index.html
sed -i -e 's/dist/javascripts/g'  math/index.html
sed -i -e 's/dist/javascripts/g'  crypto/index.html
sed -i -e 's/dist/javascripts/g'  circles/index.html
sed -i -e 's/dist/javascripts/g'  crypt/index.html
sed -i -e 's/dist/javascripts/g'  dots/index.html
sed -i -e 's/dist/javascripts/g'  vibration/index.html
sed -i -e 's/dist/javascripts/g'  mosaic/index.html
sed -i -e 's/dist/javascripts/g'  soap/index.html
sed -i -e 's/dist/javascripts/g'  wood/index.html
sed -i -e 's/dist/javascripts/g'  mosaic/index.html
sed -i -e 's/dist/javascripts/g'  wood/index.html
sed -i -e 's/dist/javascripts/g'  stack/index.html
sed -i -e 's/dist/javascripts/g'  clouds/index.html
sed -i -e 's/dist/javascripts/g'  salt/index.html
sed -i -e 's/dist/javascripts/g'  stars/index.html
sed -i -e 's/dist/javascripts/g'  shuffling/index.html

